<a href="https://colab.research.google.com/github/gokhanturer/assignment/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [6]:
import numpy as np
import pandas as pd
import scipy as sp
import statistics as st

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100, 15, 1000)
samples

array([ 94.2913749 , 112.51332905,  94.64042335, 117.98598142,
       118.15097529, 115.82473492,  96.71434244, 111.23605316,
        98.66568321,  97.41401641, 107.81493544,  98.67157263,
       100.92988944, 112.84770901, 113.41278245,  84.7658607 ,
        97.30095585,  97.76843357,  90.3256352 , 110.1142153 ,
        99.05788165,  96.69769937,  84.0944464 ,  74.90266558,
       108.15231097, 108.56674949, 111.69493123, 109.57563468,
       100.31342554,  88.68754437, 112.31094446, 100.8561909 ,
       112.92237076, 107.36393837,  80.95963442,  89.53085786,
        99.57659586, 113.52653641,  99.71971022,  83.57987034,
        80.20179553, 105.77704689,  97.22876625, 100.22388582,
       107.92624441,  82.61043123,  92.93448355,  77.94723139,
       124.03454763, 103.22848957, 114.86433782,  68.16200902,
        95.24821893, 110.99312064,  96.55190162, 105.36385788,
        99.86162412,  73.4141092 ,  94.80592887, 114.04404606,
        89.7118842 ,  84.85893259,  99.13987407, 106.66

Compute the **mean**, **median**, and **mode**

In [29]:
mean = samples.mean()
mean
median = np.median(samples)
median
mode = stats.mode(samples)
mode

ModeResult(mode=array([53.42154644]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [12]:
min = np.min(samples)
max =np.max(samples)
q1 = np.percentile(samples, 25, interpolation="midpoint")
q1
q3 = np.percentile(samples, 75, interpolation="midpoint")
q3
iqr = q3-q1
iqr

20.33989991670569

Compute the **variance** and **standard deviation**

In [28]:
variance = np.var(samples)
std_dev = np.std(samples)
std_dev
from scipy import stats as stats

Compute the **skewness** and **kurtosis**

In [35]:
skewness = stats.skew(samples, bias=False)
kurtosis = stats.kurtosis(samples)
kurtosis

-0.05258635506652665

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [21]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [23]:
y = np.array(np.linspace(1,10,10))
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [24]:
r = np.corrcoef(x,y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [25]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [27]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = stats.spearmanr(x,y)

## Seaborn Dataset Tips

Import Seaborn Library

In [37]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [39]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [40]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [43]:
np.corrcoef(tips["total_bill"],tips["tip"])

array([[1.        , 0.67573411],
       [0.67573411, 1.        ]])